module.exports = {
  up: QueryInterface => {
    return QueryInterface.bulkInsert(
      'breeds',
      [
        {
          name: 'Vira-lata (SRD)',
          specie_id: 1,
          canceled_at: null,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Shih Tzu',
          specie_id: 1,
          canceled_at: null,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Buldogue',
          specie_id: 1,
          canceled_at: null,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Buldogue Francês',
          specie_id: 1,
          canceled_at: null,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Maltês',
          specie_id: 1,
          canceled_at: null,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Pug',
          specie_id: 1,
          canceled_at: null,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Pit Bull',
          specie_id: 1,
          canceled_at: null,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Spitz Alemão',
          specie_id: 1,
          canceled_at: null,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Dachshund (Salsicha)',
          specie_id: 1,
          canceled_at: null,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Pastor-alemão',
          specie_id: 1,
          canceled_at: null,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Basset',
          specie_id: 1,
          canceled_at: null,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Schanuzer',
          specie_id: 1,
          canceled_at: null,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Poodle',
          specie_id: 1,
          canceled_at: null,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Rottweiler',
          specie_id: 1,
          canceled_at: null,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Labrador',
          specie_id: 1,
          canceled_at: null,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Pinscher',
          specie_id: 1,
          canceled_at: null,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Lhasa Apso',
          specie_id: 1,
          canceled_at: null,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Golden Retriever',
          specie_id: 1,
          canceled_at: null,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Yorkshire Terrier',
          specie_id: 1,
          canceled_at: null,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Chihuahua',
          specie_id: 1,
          canceled_at: null,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Husky Siberiano',
          specie_id: 1,
          canceled_at: null,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Shiba inu',
          specie_id: 1,
          canceled_at: null,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Beagle',
          specie_id: 1,
          canceled_at: null,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Dobermann',
          specie_id: 1,
          canceled_at: null,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Chow-chow',
          specie_id: 1,
          canceled_at: null,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Border Collie',
          specie_id: 1,
          canceled_at: null,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Boxer',
          specie_id: 1,
          canceled_at: null,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Pastor Australiano',
          specie_id: 1,
          canceled_at: null,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'São Bernardo',
          specie_id: 1,
          canceled_at: null,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Cocker',
          specie_id: 1,
          canceled_at: null,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Bull Terrier',
          specie_id: 1,
          canceled_at: null,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Pastor Belga',
          specie_id: 1,
          canceled_at: null,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Pequinês',
          specie_id: 1,
          canceled_at: null,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Vira lata (SRD)',
          specie_id: 2,
          canceled_at: null,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Maine Coon',
          specie_id: 2,
          canceled_at: null,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Gato de pelo curto inglês',
          specie_id: 2,
          canceled_at: null,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Siamês',
          specie_id: 2,
          canceled_at: null,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Ragdoll',
          specie_id: 2,
          canceled_at: null,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Gato-de-bengala',
          specie_id: 2,
          canceled_at: null,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Sphynx',
          specie_id: 2,
          canceled_at: null,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Sagrado da Birmâmia',
          specie_id: 2,
          canceled_at: null,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Gato Abissínio',
          specie_id: 2,
          canceled_at: null,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Scottish Fold',
          specie_id: 2,
          canceled_at: null,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Gato de pelo curto americano',
          specie_id: 2,
          canceled_at: null,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Norueguês da Floresta',
          specie_id: 2,
          canceled_at: null,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Azul Russo',
          specie_id: 2,
          canceled_at: null,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Siberiano',
          specie_id: 2,
          canceled_at: null,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Gato Birmanês',
          specie_id: 2,
          canceled_at: null,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Bobtail Japonês',
          specie_id: 2,
          canceled_at: null,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Himalaio',
          specie_id: 2,
          canceled_at: null,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Gato Manês',
          specie_id: 2,
          canceled_at: null,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Devon Rex',
          specie_id: 2,
          canceled_at: null,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Angorá',
          specie_id: 2,
          canceled_at: null,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Chartreux',
          specie_id: 2,
          canceled_at: null,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Gato Savannah',
          specie_id: 2,
          canceled_at: null,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Balinês',
          specie_id: 2,
          canceled_at: null,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Tonquinês',
          specie_id: 2,
          canceled_at: null,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Somali',
          specie_id: 2,
          canceled_at: null,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: 'Peterbald',
          specie_id: 2,
          canceled_at: null,
          created_at: new Date(),
          updated_at: new Date(),
        },
      ],
      {}
    );
  },

  down: () => {},
};
